#-----------------------------------------------------------
# Vivado v2018.3 (64-bit)
# SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
# IP Build 2404404 on Fri Dec  7 01:43:56 MST 2018
# Start of session at: Sun Jun 19 18:10:16 2022
# Process ID: 31164
# Current directory: C:/Users/wty02/Pictures/project_3
# Command line: vivado.exe -gui_launcher_event rodinguilauncherevent26696 C:\Users\wty02\Pictures\project_3\project_3.xpr
# Log file: C:/Users/wty02/Pictures/project_3/vivado.log
# Journal file: C:/Users/wty02/Pictures/project_3\vivado.jou
#-----------------------------------------------------------
start_gui
open_project C:/Users/wty02/Pictures/project_3/project_3.xpr
Scanning sources...
Finished scanning sources
INFO: [IP_Flow 19-234] Refreshing IP repositories
INFO: [IP_Flow 19-1704] No user IP repositories specified
INFO: [IP_Flow 19-2313] Loaded Vivado IP repository 'C:/Xilinx/Vivado/2018.3/data/ip'.
open_project: Time (s): cpu = 00:00:14 ; elapsed = 00:00:06 . Memory (MB): peak = 795.836 ; gain = 151.398
open_hw
update_compile_order -fileset sources_1
connect_hw_server
INFO: [Labtools 27-2285] Connecting to hw_server url TCP:localhost:3121
INFO: [Labtools 27-2222] Launching hw_server...
INFO: [Labtools 27-2221] Launch Output:

****** Xilinx hw_server v2018.3
  **** Build date : Dec  7 2018-00:40:27
    ** Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
ERROR: [Labtools 27-2220] Launch Error:
Unable to launch local hw_server executable.

ERROR: [Common 17-39] 'connect_hw_server' failed due to earlier errors.
exit
INFO: [Common 17-206] Exiting Vivado at Sun Jun 19 18:10:49 2022...
